exclude: [README.md]

markdown: redcarpet
redcarpet:
  extensions: [ "tables" ]

baseurl: /teststormghpages

issue_base_url: "https://issues.infn.it/browse/"
website_base_url: "http://italiangrid.github.io/storm"
repo_base_url: "https://github.com/italiangrid"

versions:
    sysadmin_guide: 1.11.2

storm_components:
    - name: StoRM Backend
      package: storm-backend-server
      latest: 1.11.2
      new: true
      repo: StoRM
      visibility: show
    - name: StoRM Frontend
      package: storm-frontend-server
      latest: 1.8.2
      new: true
      repo: StoRM
      visibility: show
    - name: StoRM GridHTTPs
      package: storm-gridhttps-server
      latest: 2.0.2
      new: true
      repo: StoRM
      visibility: show
    - name: StoRM native libs
      package: storm-native-libs
      latest: 1.0.2
      new: true
      repo: StoRM
      visibility: hide
    - name: YAIM StoRM
      package: yaim-storm
      latest: 4.3.3
      new: true
      repo: StoRM
      visibility: hide
    - name: StoRM dynamic info
      package: storm-dynamic-info-provider
      latest: 1.7.6
      new: false
      repo: StoRM emi
      visibility: hide
    - name: StoRM client
      package: storm-srm-client
      latest: 1.6.0
      new: false
      repo: StoRM emi
      visibility: hide
    - name: StoRM GridHTTPs plugin
      package: storm-gridhttps-plugin
      latest: 1.1.0
      new: false
      repo: StoRM emi
      visibility: hide
    - name: StoRM GridFTP
      package: storm-gridftp-dsi
      latest: 1.2.0
      new: false
      repo: StoRM emi
      visibility: hide
      
authors:
  andrea:
    display_name: Andrea Ceccanti
    gravatar: f371f6284e5f3b10c555a24fd728a1ef    
    email: andrea.ceccanti@cnaf.infn.it
    github: andreaceccanti
  valerio:
    display_name: Valerio Venturi
    gravatar: 25170d7bd06dd4d753053e12888d1bb0    
    email: valerio.venturi@cnaf.infn.it
    github: valerioventuri
  daniele:
    display_name: Daniele Andreotti
    email: daniele.andreotti@cnaf.infn.it
    github: dandreotti
  enrico:
    display_name: Enrico Vianello
    email: enrico.vianello@cnaf.infn.it
    gravatar: 4f496230f3e42d606024e16c5f389611
    github: enricovianello